"use server";

import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { getLocale } from "@/i18n/server";
import { recordAcceptance } from "@/lib/legal/acceptance";
import { safeInternalPath } from "@/lib/legal/safe-next";

// The authoritative clickwrap event. A server action is its own HTTP entry point, so identity
// and both attestations are re-validated HERE — a forged or incomplete POST (missing either
// checkbox, or no session) is rejected server-side regardless of what the client rendered. The
// acceptance timestamp is generated by PostgreSQL (recordAcceptance), never the browser, and the
// insert is idempotent. Acceptance is derived from the database row, not a session flag, so it is
// impossible to "mark accepted" before the insert succeeds — we only redirect onward after it does.

export interface AcceptState {
  error: string | null;
}

const CHECKBOX_YES = "yes";

export async function acceptAction(
  _prev: AcceptState | null,
  formData: FormData,
): Promise<AcceptState> {
  const session = await auth();
  const email = session?.user?.email;
  if (!email) redirect("/signin"); // no verified identity → cannot record acceptance

  // Safe internal destination only — external origins / open redirects collapse to "/".
  const safeNext = safeInternalPath(formData.get("next") as string | null);

  const adultAttested = formData.get("adult_attested") === CHECKBOX_YES;
  const privacyAcknowledged = formData.get("privacy_acknowledged") === CHECKBOX_YES;
  if (!adultAttested || !privacyAcknowledged) {
    return {
      error:
        "Please confirm you are at least 18 and agree to the Terms of Use, and acknowledge the Privacy Notice.",
    };
  }

  // Active locale is best-effort context, nullable by design.
  let locale: string | null = null;
  try {
    locale = await getLocale();
  } catch {
    locale = null;
  }

  const result = await recordAcceptance({
    email,
    adultAttested,
    privacyAcknowledged,
    locale,
    // This optional control never gates product access. Missing/malformed is an explicit denial,
    // so a prior grant cannot survive acknowledgement of the revised Privacy Notice unchecked.
    analyticsPreference:
      formData.get("analytics_preference") === "granted" ? "granted" : "denied",
  });
  if (!result.ok) {
    return { error: "We couldn't save your acceptance right now. Please try again." };
  }

  redirect(safeNext);
}
